spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_events
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Chemin de stockage - option développement (dans le projet)
app.upload.dir=./uploads/images
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# Email Configuration
# Nom de l'application
# Application
app.name=Événements-Préfecture oujda angad
app.support.email=support.evenements@interieur.gov.ma

# Configuration Gmail infaillible
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=salma70109@gmail.com
spring.mail.password=${EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000